# Database configuration
db.url=jdbc:postgresql://localhost:5432/helidon_vovk_platform
db.username=postgres
db.password=root

# JWT properties
security.providers.jwt.algorithm=HS256
security.providers.jwt.issuer=helidon-jwt-demo
security.providers.jwt.expiration-seconds=3600
security.providers.jwt.signing-key-resource=jwt-keys.json
security.providers.jwt.verify-key-resource=jwt-keys.json

# OpenAPI configuration
server.features.openapi.web-context=/openapi
server.features.openapi.static-file=META-INF/openapi.yml

# Swagger UI
server.features.openapi.ui.enabled=true
server.features.openapi.ui.web-context=/ui