# ===============================
# Database configuration
# ===============================
db.url=jdbc:postgresql://localhost:5432/helidon_vovk_platform
db.username=postgres
db.password=root

# ===============================
# JWT configuration
# ===============================
security.providers.jwt.issuer=helidon-jwt-demo
security.providers.jwt.verify-key-resource=jwt-keys.json