# ===============================
# Database configuration
# ===============================
db.url=${DB_URL:jdbc:postgresql://helidon-db:5432/helidon_vovk_platform}
db.username=${DB_USERNAME:postgres}
db.password=${DB_PASSWORD:root}

# ===============================
# JWT configuration
# ===============================
security.providers.jwt.issuer=helidon-jwt-demo
security.providers.jwt.verify-key-resource=jwt-keys.json

# ===============================
# OpenAPI configuration
# ===============================
server.features.openapi.web-context=${OPENAPI_CONTEXT:/openapi}
server.features.openapi.static-file=${OPENAPI_STATIC_FILE:META-INF/openapi.yml}

# ===============================
# Swagger UI
# ===============================
server.features.openapi.ui.enabled=${OPENAPI_UI_ENABLED:true}
server.features.openapi.ui.web-context=${OPENAPI_UI_CONTEXT:/ui}