# Database configuration
db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}

# JWT properties
security.providers.jwt.issuer=${JWT_ISSUER:helidon-jwt-demo}
security.providers.jwt.verify-key-resource=${JWT_VERIFY_KEY_RESOURCE:jwt-keys.json}

# OpenAPI configuration
server.features.openapi.web-context=${OPENAPI_CONTEXT:/openapi}
server.features.openapi.static-file=${OPENAPI_STATIC_FILE:META-INF/openapi.yml}

# Swagger UI
server.features.openapi.ui.enabled=${OPENAPI_UI_ENABLED:true}
server.features.openapi.ui.web-context=${OPENAPI_UI_CONTEXT:/ui}